const actionsTypes = {
    SET_PRODUCT: 'SET_PRODUCT',
    ADD_TO_CART: 'ADD_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    SET_QTY: 'SET_QTY',
    INCREMENT_PRODUCT: 'INCREMENT_PRODUCT',
    DECREMENT_PRODUCT: 'DECREMENT_PRODUCT',
    CLEAR_CART: 'CLEAR_CART'
}

export { actionsTypes }